# api http test requests for VSCode rest client


### get cats Assignment 2
GET http://localhost:3000/api/v1/cat

### get cat by id Assignment 2
GET http://localhost:3000/api/v1/cat/99

### post new cat Assignment 2
POST http://localhost:3000/api/v1/cat
Content-Type: application/json

{
  "name": "New Cat",
  "birthdate": "2022-01-01",
  "weight": 5,
  "owner": "Owner Name",
  "image": "https://loremflickr.com/320/240/cat"
}

### get users Assignment 2
GET http://localhost:3000/api/v1/user

### get user by id Assignment 2
GET http://localhost:3000/api/v1/user/2

### post new user Assignment 2
POST http://localhost:3000/api/v1/user
Content-Type: application/json

{
  "user_id": 99,
  "name": "John 99",
  "username": "johndoe",
  "email": "john@metropolia.fi",
  "role": "user",
  "password": "password"
}

